version: "3"

tasks:
  # Task to start the Node.js timer service
  start-timer-service:
    desc: Run the Node timer service
    cmds:
      - node server.js

  start:
    desc: Run the Node timer service
    cmds:
      - task: start-timer-service
